config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'

  devise_for :users
  resources :posts do 
  	resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, 	except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]


	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(params.require(:post).permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy

		redirect_to root_path

	end

	private
	
		def post_params
			params.require(:post).permit(:title, :body)
		end

		def find_post
			@post = Post.find(params[:id])
		end

		def require_same_user
      # set restriction for editing articles only to the one created them
      if current_user.id != @post.user_id
        flash = "You can only edit or delete your own post"
        redirect_to root_path
      end
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>	
		<p><%= link_to "Delete", post_comment_path(@post, comment), method: :delete, class: "button", data: { confirm: "Are you sure?"} %></p>
		<!-- Alternative -->
		<!-- <p><%= link_to "Delete", [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure?"} %></p> -->
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Railway:400,700' %>
  <%= favicon_link_tag 			 'favicon.ico' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<ul>
			<li class="category"><%= link_to "Tumblr", root_path %></li>
			<li><%= link_to "Posts", root_path %></li>
			<li><%= link_to "About", about_path %> 
			<% if user_signed_in? %>
				<p class="sign_in"><%=current_user.email%></p>
			<% elsif %>
				<p class="sign_in"><%= link_to "User Login", new_user_session_path %></p> 
			<% end %>
		</ul>
	</div>

	<div id="main_content">
		<div id="header">

			<% if current_page?(root_path) %>
				<p>Post Feed</p>
			<% elsif current_page?(about_path) %>
				<p>My Site</p>
			<% else %>
				<%= link_to "Back to Post Feed", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
					<!-- <button class="button"><%= link_to "Make Post", new_post_path %></button> -->
					<%= link_to "Make Post", new_post_path, class: "button" %>
					<%= link_to "Sign Out", destroy_user_session_path, class: "button", method: :delete %> 
				<!-- <button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></button> -->

				</div>
			<% end %>


		</div>
		

		<% flash.each do |name,msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
 <div id="profile_image">
  <%= image_tag "profile.jpeg" %>
 </div>

 <div id="content">
  <h1>It's Mr. Stick Figure</h1>
  </p>Schlitz 8-bit selfies try-hard fingerstache. Cardigan squid selfies venmo pork belly ennui. Shoreditch marfa butcher, whatever mumblecore migas heirloom yuccie ugh. Yuccie sustainable PBR&B kinfolk, cold-pressed put a bird on it banh mi affogato. Flannel man bun master cleanse, jean shorts paleo keytar kitsch +1 green juice forage blog fixie DIY. Art party bushwick wayfarers deep v vice 8-bit. Crucifix lumbersexual bitters cray, wayfarers food truck cliche kogi irony.
  </p>
 </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">	
	<h1>Fix Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 clas="title"><%= link_to post.title, post %></h2>
		<p class="body"><%= truncate(post.body, length: 100) %></p>
		<p class="date"><%= time_ago_in_words(post.created_at) %> ago by <%= post.user.email %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">	
	<h1>Make something</h1>

	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>
		
		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.email %>
		<% if user_signed_in? && (current_user.id == @post.user_id) %>	
			<%= link_to "Edit", edit_post_path(@post) %> |
			<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
		<% end %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
		<h3> Join Discussion: </h3>
		<%= render 'comments/form' %>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>